name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  fpdart: ^0.0.14
  freezed_annotation: ^1.1.0
  kt_dart: ^0.10.0
  modddels_annotations:
    git:
      url: git://github.com/ojm-it/modddels.git
      ref: master
      path: modddels_annotations

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  modddels_generator:
    git:
      url: git://github.com/ojm-it/modddels.git
      ref: master
      path: modddels_generator

flutter:
  uses-material-design: true
