targets:
  $default:
    builders:
      modddels_generator:
        enabled: true

builders:
  modddels_generator:
    import: "package:modddels_generator/builder.dart"
    builder_factories: ["generateModddel"]
    build_extensions: { ".dart": [".modddel.dart"] }
    auto_apply: dependents
    build_to: source
    required_inputs: [".freezed.dart"]
