name: modddels_generator
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.7.0
  build: ^2.1.1
  source_gen: ^1.1.1
  modddels_annotations:
      git:
          url: git://github.com/ojm-it/modddels.git
          ref: master
          path: modddels_annotations

dev_dependencies:
  build_runner: ^2.1.5
  build_test: ^2.1.4
  flutter_lints: ^1.0.0
  test: ^1.19.4
