import 'package:flutter_test/flutter_test.dart';
import 'package:collection/collection.dart';
import 'package:modddels_annotations/modddels.dart';
import 'package:modddels_annotations/src/testers/common.dart';
import 'package:modddels_annotations/src/testers/entities_testers/test_cases.dart';
import 'package:modddels_annotations/src/testers/testers_utils.dart';

/// This is a mixin for Entity Testers that need to test that an entity SUT
/// is a [ValidEntity].
mixin ValidTesterMixin<I extends InvalidEntity, V extends ValidEntity,
    E extends Modddel<I, V>> {
  /// See [Tester.maxSutDescriptionLength]
  int get maxSutDescriptionLength;

  /// This is the description of the [group] generated by the
  /// [makeIsValidTestGroup] method.
  String get isValidGroupDescription;

  /// The [entity] should be valid.
  void expectIsValid({required E entity}) {
    expect(entity, isA<V>());
    expect(entity.isValid, true);
  }

  /// Generates a [group] that contains all the TestIsValidEntity [tests].
  ///
  /// The [group]'s description is set to [isValidGroupDescription], but you can
  /// override it by providing your own [description].
  ///
  /// If [maxSutDescriptionLength] is provided, then it overrides the value
  /// of this tester's [Tester.maxSutDescriptionLength].
  ///
  /// For documentation of [description] and [skip], see [group].
  void makeIsValidTestGroup({
    required List<TestIsValidEntity<E>> tests,
    int? maxSutDescriptionLength,
    Object? description,
    dynamic skip,
  }) {
    assert(maxSutDescriptionLength == null ||
        maxSutDescriptionLength > 0 ||
        maxSutDescriptionLength == TesterUtils.noEllipsis);

    group(
      description ?? isValidGroupDescription,
      () {
        for (final _test in tests) {
          final entity = _test.sut;

          final maxLength =
              maxSutDescriptionLength ?? this.maxSutDescriptionLength;

          final description = '- "${TesterUtils.formatObject(
            entity,
            maxLength: maxLength,
          )}"';
          final finalDescription = _test.getFinalDescription(description);
          test(
            finalDescription,
            () {
              expectIsValid(entity: entity);
            },
            testOn: _test.testOn,
            timeout: _test.timeout,
            skip: _test.skip,
            tags: _test.tags,
            onPlatform: _test.onPlatform,
            retry: _test.retry,
          );
        }
      },
      skip: skip,
    );
  }
}

/// This is a mixin for Entity Testers that need to test that an entity SUT
/// is an [InvalidEntityContent].
mixin ContentTesterMixin<C extends InvalidEntityContent,
    I extends InvalidEntity, V extends ValidEntity, E extends Modddel<I, V>> {
  /// See [Tester.maxSutDescriptionLength]
  int get maxSutDescriptionLength;

  /// This is the description of the [group] generated by the
  /// [makeIsInvalidContentTestGroup] method.
  String get isInvalidContentGroupDescription;

  /// The [entity] should be an [InvalidEntityContent] and hold the
  /// [contentFailure].
  void expectIsInvalidContent(
      {required E entity, required Failure contentFailure}) {
    expect(entity, isA<C>());
    expect(entity.isValid, false);
    expect((entity as C).contentFailure, contentFailure);
  }

  /// Generates a [group] that contains all the TestIsInvalidContent [tests].
  ///
  /// The [group]'s description is set to [isInvalidContentGroupDescription],
  /// but you can override it by providing your own [description].
  ///
  /// If [maxSutDescriptionLength] is provided, then it overrides the value
  /// of this tester's [Tester.maxSutDescriptionLength].
  ///
  /// For documentation of [description] and [skip], see [group].
  void makeIsInvalidContentTestGroup({
    required List<TestIsInvalidContent<E>> tests,
    int? maxSutDescriptionLength,
    Object? description,
    dynamic skip,
  }) {
    assert(maxSutDescriptionLength == null ||
        maxSutDescriptionLength > 0 ||
        maxSutDescriptionLength == TesterUtils.noEllipsis);

    group(
      description ?? isInvalidContentGroupDescription,
      () {
        for (final _test in tests) {
          final entity = _test.sut;

          final maxLength =
              maxSutDescriptionLength ?? this.maxSutDescriptionLength;

          final description = '- "${TesterUtils.formatObject(
            entity,
            maxLength: maxLength,
          )}"';
          final finalDescription = _test.getFinalDescription(description);
          test(
            finalDescription,
            () {
              expectIsInvalidContent(
                  entity: entity, contentFailure: _test.contentFailure);
            },
            testOn: _test.testOn,
            timeout: _test.timeout,
            skip: _test.skip,
            tags: _test.tags,
            onPlatform: _test.onPlatform,
            retry: _test.retry,
          );
        }
      },
      skip: skip,
    );
  }
}

/// This is a mixin for Entity Testers that need to test that an entity SUT
/// is an [InvalidEntityGeneral].
mixin GeneralTesterMixin<
    F extends GeneralFailure,
    G extends InvalidEntityGeneral<F>,
    I extends InvalidEntity,
    V extends ValidEntity,
    E extends Modddel<I, V>> {
  /// See [Tester.maxSutDescriptionLength]
  int get maxSutDescriptionLength;

  /// This is the description of the [group] generated by the
  /// [makeIsInvalidGeneralTestGroup] method.
  String get isInvalidGeneralGroupDescription;

  /// The [entity] should be an [InvalidEntityGeneral] and hold the
  /// [generalFailure].
  void expectIsInvalidGeneral({required E entity, required F generalFailure}) {
    expect(entity, isA<G>());
    expect(entity.isValid, false);
    expect((entity as G).generalFailure, generalFailure);
  }

  /// Generates a [group] that contains all the TestIsInvalidGeneral [tests].
  /// The tests that concern the same [GeneralFailure] union-case are grouped
  /// into the same subgroups.
  ///
  /// The [group]'s description is set to [isInvalidGeneralGroupDescription],
  /// but you can override it by providing your own [description]. Each
  /// subgroup's description is the formatted className of the [GeneralFailure]
  /// union-case.
  ///
  /// If [maxSutDescriptionLength] is provided, then it overrides the value
  /// of this tester's [Tester.maxSutDescriptionLength].
  ///
  /// For documentation of [description] and [skip], see [group].
  void makeIsInvalidGeneralTestGroup({
    required List<TestIsInvalidGeneral<E, F>> tests,
    int? maxSutDescriptionLength,
    Object? description,
    dynamic skip,
  }) {
    assert(maxSutDescriptionLength == null ||
        maxSutDescriptionLength > 0 ||
        maxSutDescriptionLength == TesterUtils.noEllipsis);

    group(
      description ?? isInvalidGeneralGroupDescription,
      () {
        /// The keys are the [GeneralFailure] union-cases classNames, and the
        /// values are the tests that concern each [GeneralFailure] union-case.
        final testGroups = groupBy<TestIsInvalidGeneral<E, F>, String>(
          tests,
          (test) => TesterUtils.formatFailure(test.generalFailure),
        );

        testGroups.forEach((key, value) {
          group(
            '"$key"',
            () {
              for (final _test in value) {
                final entity = _test.sut;

                final maxLength =
                    maxSutDescriptionLength ?? this.maxSutDescriptionLength;

                final description = '- "${TesterUtils.formatObject(
                  entity,
                  maxLength: maxLength,
                )}"';
                final finalDescription = _test.getFinalDescription(description);
                test(
                  finalDescription,
                  () {
                    expectIsInvalidGeneral(
                        entity: entity, generalFailure: _test.generalFailure);
                  },
                  testOn: _test.testOn,
                  timeout: _test.timeout,
                  skip: _test.skip,
                  tags: _test.tags,
                  onPlatform: _test.onPlatform,
                  retry: _test.retry,
                );
              }
            },
          );
        });
      },
      skip: skip,
    );
  }
}

/// This is a mixin for Entity Testers that need to test that an entity SUT
/// is an [InvalidEntitySize].
mixin SizeTesterMixin<F extends SizeFailure, S extends InvalidEntitySize<F>,
    I extends InvalidEntity, V extends ValidEntity, E extends Modddel<I, V>> {
  /// See [Tester.maxSutDescriptionLength]
  int get maxSutDescriptionLength;

  /// This is the description of the [group] generated by the
  /// [makeIsInvalidSizeTestGroup] method.
  String get isInvalidSizeGroupDescription;

  /// The [entity] should be an [InvalidEntitySize] and hold the [sizeFailure].
  void expectIsInvalidSize({required E entity, required F sizeFailure}) {
    expect(entity, isA<S>());
    expect(entity.isValid, false);
    expect((entity as S).sizeFailure, sizeFailure);
  }

  /// Generates a [group] that contains all the TestIsInvalidSize [tests]. The
  /// tests that concern the same [SizeFailure] union-case are grouped into the
  /// same subgroups.
  ///
  /// The [group]'s description is set to [isInvalidSizeGroupDescription], but
  /// you can override it by providing your own [description]. Each subgroup's
  /// description is the formatted className of the [SizeFailure] union-case.
  ///
  /// If [maxSutDescriptionLength] is provided, then it overrides the value
  /// of this tester's [Tester.maxSutDescriptionLength].
  ///
  /// For documentation of [description] and [skip], see [group].
  void makeIsInvalidSizeTestGroup({
    required List<TestIsInvalidSize<E, F>> tests,
    int? maxSutDescriptionLength,
    Object? description,
    dynamic skip,
  }) {
    assert(maxSutDescriptionLength == null ||
        maxSutDescriptionLength > 0 ||
        maxSutDescriptionLength == TesterUtils.noEllipsis);

    group(
      description ?? isInvalidSizeGroupDescription,
      () {
        final testGroups = groupBy<TestIsInvalidSize<E, F>, String>(
          tests,
          (test) => TesterUtils.formatFailure(test.sizeFailure),
        );

        testGroups.forEach((key, value) {
          group(
            '"$key"',
            () {
              for (final _test in value) {
                final entity = _test.sut;

                final maxLength =
                    maxSutDescriptionLength ?? this.maxSutDescriptionLength;

                final description = '- "${TesterUtils.formatObject(
                  entity,
                  maxLength: maxLength,
                )}"';
                final finalDescription = _test.getFinalDescription(description);
                test(
                  finalDescription,
                  () {
                    expectIsInvalidSize(
                        entity: entity, sizeFailure: _test.sizeFailure);
                  },
                  testOn: _test.testOn,
                  timeout: _test.timeout,
                  skip: _test.skip,
                  tags: _test.tags,
                  onPlatform: _test.onPlatform,
                  retry: _test.retry,
                );
              }
            },
          );
        });
      },
      skip: skip,
    );
  }
}
