import 'package:flutter/foundation.dart';
import 'package:modddels_annotations/src/testers/core/testers_utils.dart';

/// This is the base class of all the Testers. A [Tester] is an object used
/// to easily unit test modddels.
@immutable
abstract class Tester {
  const Tester({required this.maxSutDescriptionLength})
      : assert(maxSutDescriptionLength > 0 ||
            maxSutDescriptionLength == TesterUtils.noEllipsis);

  /// The tests generated by the methods of this Tester have a description that
  /// usually contains the String representation of the SUT.
  ///
  /// This [maxSutDescriptionLength] is the maximum length of that String,
  /// beyond which it is ellipsized.
  ///
  /// You can disable this "ellipsisation" by setting [maxSutDescriptionLength]
  /// to [TesterUtils.noEllipsis].
  final int maxSutDescriptionLength;
}
